name: Release

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack Futurum.Core
        run: dotnet pack ./src/Futurum.Core/Futurum.Core.csproj --output nuget-packages --configuration Release
      - name: NuGet publish
        run: find nuget-packages -name 'Futurum.Core*.nupkg' | xargs -i dotnet nuget push {} --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-packages
          path: nuget-packages/**/*